@url = http://localhost:5000

###
GET {{url}}

###
GET {{url}}/api/v1/assets

###
POST {{url}}/api/v1/assets
Content-Type: application/json

{
    "Name": "eth",
    "Change": 0.05,
    "Start": "2022-12-05T00:00:00",
    "End": "2022-12-12T00:00:00"
}

###
POST {{url}}/api/v1/monitors/start
Content-Type: application/json

{
    "Name": "eth3312"
}

###
POST {{url}}/api/v1/monitors/stop
Content-Type: application/json

{
    "Name": "eth"
}