@url = http://localhost:5005

###
GET {{url}}

###
GET {{url}}/api/v1/assets

###
POST {{url}}/api/v1/assets
Content-Type: application/json

{
    "Name": "ETH",
    "Change": 0.05,
    "End": "2022-12-12T00:00:00"
}

###
POST {{url}}/api/v1/monitors/start
Content-Type: application/json

{
    "Name": "MartutCoin"
}

###
POST {{url}}/api/v1/monitors/stop
Content-Type: application/json

{
    "Name": "MartutCoin"
}