version: '3'

services:
  redis:
    image: redis:7.0
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}

networks:
  nQuadro:
    name: nQuadro
    external: true
